# Generated by Django 2.2.1 on 2019-06-19 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnersAPI', '0002_auto_20190619_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to=settings.AUTH_USER_MODEL),
        ),
    ]
